version: "3"

services:
  app:
    image: foxy-uam:v1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host